name: 1 - hello - world

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print hello
              run: echo "Hello World"


    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print hi to you
              run: echo "Hi, u"

            - name: I will fail
              run: exec 1

            - name: Say Goodbye
              run: echo "Goodbye"



